# Generated by Django 3.1.5 on 2021-03-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikuwrites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='Hindi', max_length=255),
        ),
    ]
